Bilgi/Bilgi.Web/Controllers/Accounts/LoginController.cs
using Bilgi.Data.Access.Layer.Identity.Models;
using Bilgi.Web.ViewModel;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.DotNet.Scaffolding.Shared.Project;
using Microsoft.Identity.Client;

namespace Bilgi.Web.Controllers.Accounts
{
    public class LoginController : Controller
    {
		private readonly UserManager<AppUser> _userManager;
		private readonly SignInManager<AppUser> _signInManager;

		public LoginController(UserManager<AppUser> userManager, SignInManager<AppUser> signInManager)
		{
			_userManager = userManager;
			_signInManager = signInManager;
		}
		[HttpGet]
		public IActionResult Index()
		{
			return View();
		}
		[HttpPost]
		public async Task<IActionResult> Index(LoginViewModel model)
		{
			var user = await _userManager.FindByEmailAsync(model.Email);  //tüm kullanıcılarda e maile göre kayıt aranır
			if (user == null)
			{
				ModelState.AddModelError("", "Kayıtlı Kullanıcı Bulunamadı");   //kayıt null gelirse
				return View(model);	
			}
			var girisDeneme = await _signInManager.PasswordSignInAsync(user, model.Sifre, false, false); // kayıtlı kullanıcıya ait şifre kontrolü
			if (girisDeneme.Succeeded)
			{
				return Redirect(model.ReturnUrl ?? "/Anasayfa/Index");  //yönlendirilmiş ise o sayfaya değil ise ana sayfaya gider
			}
			else
			{
				ModelState.AddModelError("","Kullanıcı Adı veya Şifre Yanlış");
				return View(model);
			}
			
			
		}
		public async Task<IActionResult> Cikis()
		{
            await _signInManager.SignOutAsync();
            return RedirectToAction("Index", "Anasayfa");
		}
	}
}

Bilgi/Bilgi.Web/Controllers/Main/AnasayfaController.cs
using Microsoft.AspNetCore.Mvc;

namespace Bilgi.Web.Controllers.Main
{
    public class AnasayfaController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

Bilgi/Bilgi.Web/Controllers/Main/IletisimController.cs
using Microsoft.AspNetCore.Mvc;

namespace Bilgi.Web.Controllers.Main
{
    public class IletisimController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

Bilgi/Bilgi.Web/Controllers/Main/SepetController.cs
using AutoMapper;
using Bilgi.Entity.Layer.Entities;
using Bilgi.Service.Layer.Services.Abstract;
using Bilgi.Web.Extensions;
using Bilgi.Web.ViewModel;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System.Net;

namespace Bilgi.Web.Controllers.Main
{
    public class SepetController : Controller
    {
        private readonly IUrunService _urunService;
        private readonly ISepetDetayService _sepetDetayService;
        private readonly IMapper _mapper;
    
        List<SepetDetayViewModel> sepet;

        public SepetController(IUrunService urunService, ISepetDetayService sepetDetayService,IMapper mapper)
        {
            _urunService = urunService;
            _sepetDetayService = sepetDetayService;
            _mapper = mapper;           

        }

        public IActionResult Index()
        {
           
            sepet = SepetAl();
            decimal toplam = 0;
            foreach (var item in sepet)
            {
                toplam += item.ToplamTutar;
            }
            ViewBag.toplam = toplam.ToString("C");
            return View(sepet);
        }
        private List<SepetDetayViewModel> SepetAl()
        { 
            var sepet = HttpContext.Session.GetJson<List<SepetDetayViewModel>>("sepet") ?? new List<SepetDetayViewModel>();  //sepet varsa olan sepet yoksa yeni sepet oluşturularak verilir
            return sepet;
        }
      
        public IActionResult SepeteEkle(int id, int Adet)
        {
           
            var urun = _urunService.TGetByIdFiltre(x => x.Id == id && x.SatisDurum==true);  //id den ürün bulunur
            sepet = SepetAl();   //sepet alınır
            SepetDetay siparis = new SepetDetay();   //yeni detay oluşturulur ve içeriği doldurulur
            siparis.Urun = urun;
            siparis.UrunId = urun.Id;
            siparis.Adet = Adet;
            siparis.BirimFiyat = urun.Fiyat;
          
            sepet = _mapper.Map<List<SepetDetayViewModel>>( _sepetDetayService.SepeteEkle(_mapper.Map<List<SepetDetay>>(sepet), siparis)); //sepete yeni detay eklenir
            SepetKaydet(sepet);  //sepet kaydedilir
            return RedirectToAction("Index");  //sepet gösterilir


        }
        public void SepetKaydet(List<SepetDetayViewModel> sepet)
        {
            HttpContext.Session.SetJson("sepet",  (_mapper.Map<List<SepetDetay>>( sepet))); //sepet sessiona kaydedilir
        }
        public IActionResult SepettenSil(int id)
        {
            sepet = SepetAl(); // sepeti al
            sepet.RemoveAll(x => x.UrunId==id); //ürünü sepetten sil
            SepetKaydet(sepet);  //sepeti kaydet
            return RedirectToAction("Index");
        }
        public void AdetGuncelle(int id,int adet)
        {
            sepet = SepetAl();
          var urun = sepet.Find(x => x.UrunId==id);
            urun.ToplamTutar = adet * urun.BirimFiyat;
            urun.Adet=adet;

            SepetKaydet(sepet);
    

        }

        public IActionResult GuncelSepet()   //ajax ile sepeti güncellemek için
        {
            sepet = SepetAl();
            return PartialView("_SepetPartialView", sepet);
        }
        public IActionResult GuncelSepetSayisi()  //ajax ile sepet ürün sayısını güncellemek için
        {
            
            return ViewComponent("SepetSayi");
        }



    }
}

Bilgi/Bilgi.Web/Views/Shared/_AdminUrunListesi.cshtml
@model IEnumerable<UrunViewModel>
<table class="table table-striped" id="urunlerliste">
    <thead>
        <tr>

            <th> Adı </th>
            <th> Stok Sayısı </th>
            <th> Fiyatı </th>
            <th> Satış Durumu </th>
        </tr>
    </thead>
    <tbody >
        @foreach (var item in Model)
        {
            <tr>

                <td> @item.Adi </td>
                <td>
                    @item.Stok
                </td>
                <td> @item.Fiyat.ToString("C") </td>
                <td><label class="@(item.SatisDurum==true?"badge badge-success":"badge badge-danger")">@(item.SatisDurum == true ? "Satışta" : "Satışa Kapalı")</label></td>
                <td>
                    <a onclick="durumGuncelle('@item.Id')" class=" btn btn-outline-@(item.SatisDurum==false?"success":"danger")">@(item.SatisDurum == true ? "Kaldır" : "Ekle")</a>
                    <a class=" btn btn-outline-primary" asp-action="UrunGuncelle" asp-controller="urun" asp-route-id="@item.Id">Özellikler</a>
                </td>
            </tr>

        }
    </tbody>
</table>

Bilgi/Bilgi.Web/Views/Shared/_FiltreSonucPartialView.cshtml
@model IEnumerable<UrunViewModel>

@foreach (var item in Model)
{
    <div class="col-6 col-md-4 col-xl-3">

        <div class="product">
            <figure class="product-media">

                <a asp-action="Index" asp-controller="UrunDetay" asp-route-id="@item.Id">
                    <img src="@item.ResimUrlKucuk" alt="@item.ResimBaslik" class="product-image">
                </a>

                <div class="product-action">
                    <a href="#" class="btn-product btn-cart" title="Add to cart"><span>Sepete Ekle</span></a>
                </div><!-- End .product-action -->
            </figure><!-- End .product-media -->

            <div class="product-body">
                <div class="product-cat">
                    <a href="#">Bilgisayar</a>
                </div><!-- End .product-cat -->

                <h3 class="product-title"><a asp-action="Index" asp-controller="UrunDetay" asp-route-id="@item.Id">@item.Adi</a></h3>

                <!-- End .product-title -->

                <div class="product-price">
                    <span class="price"></span>
                    @item.Fiyat.ToString("C")
                </div><!-- End .product-price -->

            </div><!-- End .product-body -->
        </div>

        <!-- End .product -->

    </div>

    <!-- End .col-sm-6 col-md-4 col-xl-3 -->
}

Bilgi/Bilgi.Web/Views/Shared/_FooterPartialView.cshtml
@{   
    Layout = null;
}



<footer class="footer footer-2" style="background-color:#333!important">

    <div class="footer-middle border-0">
        <div class="container">
            <div class="row">
                <div class="col-sm-12 col-lg-6">
                    <div class="widget widget-about">
                        <img src="assets/images/demos/demo-13/logo-footer.png" class="footer-logo" alt="Footer Logo" width="105" height="25">
                        <p>Praesent dapibus, neque id cursus ucibus, tortor neque egestas augue, eu vulputate magna eros eu erat. Aliquam erat volutpat. Nam dui mi, tincidunt quis, accumsan porttitor, facilisis luctus, metus. </p>

                        <div class="widget-about-info">
                            <div class="row">
                                <div class="col-sm-6 col-md-4">
                                    <span class="widget-about-title">Got Question? Call us 24/7</span>
                                    <a href="tel:123456789">+0123 456 789</a>
                                </div><!-- End .col-sm-6 -->
                                <div class="col-sm-6 col-md-8">
                                    <span class="widget-about-title">Payment Method</span>
                                    <figure class="footer-payments">
                                        <img src="assets/images/payments.png" alt="Payment methods" width="272" height="20">
                                    </figure><!-- End .footer-payments -->
                                </div><!-- End .col-sm-6 -->
                            </div><!-- End .row -->
                        </div><!-- End .widget-about-info -->
                    </div><!-- End .widget about-widget -->
                </div><!-- End .col-sm-12 col-lg-3 -->

                <div class="col-sm-4 col-lg-2">
                    <div class="widget">
                        <h4 class="widget-title">Information</h4><!-- End .widget-title -->

                        <ul class="widget-list">
                            <li><a href="about.html">About Molla</a></li>
                            <li><a href="#">How to shop on Molla</a></li>
                            <li><a href="faq.html">FAQ</a></li>
                            <li><a href="contact.html">Contact us</a></li>
                            <li><a href="login.html">Log in</a></li>
                        </ul><!-- End .widget-list -->
                    </div><!-- End .widget -->
                </div><!-- End .col-sm-4 col-lg-3 -->

                <div class="col-sm-4 col-lg-2">
                    <div class="widget">
                        <h4 class="widget-title">Customer Service</h4><!-- End .widget-title -->

                        <ul class="widget-list">
                            <li><a href="#">Payment Methods</a></li>
                            <li><a href="#">Money-back guarantee!</a></li>
                            <li><a href="#">Returns</a></li>
                            <li><a href="#">Shipping</a></li>
                            <li><a href="#">Terms and conditions</a></li>
                            <li><a href="#">Privacy Policy</a></li>
                        </ul><!-- End .widget-list -->
                    </div><!-- End .widget -->
                </div><!-- End .col-sm-4 col-lg-3 -->

                <div class="col-sm-4 col-lg-2">
                    <div class="widget">
                        <h4 class="widget-title">My Account</h4><!-- End .widget-title -->

                        <ul class="widget-list">
                            <li><a href="#">Sign In</a></li>
                            <li><a href="cart.html">View Cart</a></li>
                            <li><a href="#">My Wishlist</a></li>
                            <li><a href="#">Track My Order</a></li>
                            <li><a href="#">Help</a></li>
                        </ul><!-- End .widget-list -->
                    </div><!-- End .widget -->
                </div><!-- End .col-sm-64 col-lg-3 -->
            </div><!-- End .row -->
        </div><!-- End .container -->
    </div><!-- End .footer-middle -->

    <div class="footer-bottom">
        <div class="container">
            <p class="footer-copyright">Copyright © 2019 Molla Store. All Rights Reserved.</p><!-- End .footer-copyright -->
            <ul class="footer-menu">
                <li><a href="#">Terms Of Use</a></li>
                <li><a href="#">Privacy Policy</a></li>
            </ul><!-- End .footer-menu -->

            <div class="social-icons social-icons-color">
                <span class="social-label">Social Media</span>
                <a href="#" class="social-icon social-facebook" title="Facebook" target="_blank"><i class="icon-facebook-f"></i></a>
                <a href="#" class="social-icon social-twitter" title="Twitter" target="_blank"><i class="icon-twitter"></i></a>
                <a href="#" class="social-icon social-instagram" title="Instagram" target="_blank"><i class="icon-instagram"></i></a>
                <a href="#" class="social-icon social-youtube" title="Youtube" target="_blank"><i class="icon-youtube"></i></a>
                <a href="#" class="social-icon social-pinterest" title="Pinterest" target="_blank"><i class="icon-pinterest"></i></a>
            </div><!-- End .soial-icons -->
        </div><!-- End .container -->
    </div><!-- End .footer-bottom -->
</footer><!-- End .footer -->

Bilgi/Bilgi.Web/Views/Shared/_HeaderPatrialView.cshtml
<header class="header header-10 header-intro-clearance">

    <div class="header-middle">
        <div class="container">
            <div class="header-left">
                <button class="mobile-menu-toggler">
                    <span class="sr-only">Toggle mobile menu</span>
                    <i class="icon-bars"></i>
                </button>

                <a asp-action="Index" asp-controller="Anasayfa" class="logo">
                    <img src="~/images/oie_transparent.png" alt="Molla Logo" width="190" height="25">
                </a>
            </div><!-- End .header-left -->

            <div class="header-center">
                <div class="header-search header-search-extended header-search-visible header-search-no-radius d-none d-lg-block">
                    <a href="#" class="search-toggle" role="button"><i class="icon-search"></i></a>
                    <form asp-controller ="UrunlerListesi" asp-action="Index" method="get">
                        <div class="header-search-wrapper search-wrapper-wide">
                        @*     <div class="select-custom">
                                <select id="cat" name="cat">
                                    <option value="">All Departments</option>
                                    <option value="1">Fashion</option>
                                    <option value="2">- Women</option>
                                    <option value="3">- Men</option>
                                    <option value="4">- Jewellery</option>
                                    <option value="5">- Kids Fashion</option>
                                    <option value="6">Electronics</option>
                                    <option value="7">- Smart TVs</option>
                                    <option value="8">- Cameras</option>
                                    <option value="9">- Games</option>
                                    <option value="10">Home &amp; Garden</option>
                                    <option value="11">Motors</option>
                                    <option value="12">- Cars and Trucks</option>
                                    <option value="15">- Boats</option>
                                    <option value="16">- Auto Tools &amp; Supplies</option>
                                </select>
                            </div><!-- End .select-custom --> *@
                            <label for="q" class="sr-only">Search</label>
                            <input type="search" class="form-control" name="ara" id="q" placeholder="Ürün Ara ..." required>
                            <button class="btn btn-primary" type="submit"><i class="icon-search"></i></button>
                        </div><!-- End .header-search-wrapper -->
                    </form>
                </div><!-- End .header-search -->
            </div>

            <div class="header-right">
                <div class="header-dropdown-link">
                    @if (User.Identity!.IsAuthenticated)
                    {
                        <div class="dropdown compare-dropdown">
                            <a asp-controller="Profil" asp-action="Index" class="dropdown-toggle" role="button" aria-haspopup="true" aria-expanded="false" data-display="static" title="Compare Products" aria-label="Compare Products">
                                <i class="icon-user"></i>
                                <span class="compare-txt">@User.Identity.Name</span>
                            </a>
                            <div class="dropdown-menu dropdown-menu-right">


                                <div class="compare-actions">
                                    <a asp-controller="Profil" asp-action="Index" class="btn btn-outline-primary-2"><span>Profilim</span><i class="icon-user"></i></a>
                                    <a asp-controller="Login" asp-action="Cikis" class="btn btn-outline-primary-2"><span>Çıkış Yap</span><i class="icon-long-arrow-right"></i></a>
                                </div>
                            </div><!-- End .dropdown-menu -->

                        </div>
                      

                        <!-- End .compare-dropdown -->

                        <!-- End .compare-dropdown -->
                    }else
                    {
                        <div class="dropdown compare-dropdown">
                            <a asp-controller="Login" asp-action="Index" class="dropdown-toggle" role="button" aria-haspopup="true" aria-expanded="false" data-display="static" title="Compare Products" aria-label="Compare Products">
                                <i class="icon-user"></i>
                                <span class="compare-txt">Giriş yap</span>
                            </a>

                        </div>

                        <!-- End .compare-dropdown -->
                    }       
             

                   
                    <div class="dropdown cart-dropdown">
                        <a asp-controller="Sepet" asp-action="Index" class="dropdown-toggle" role="button" aria-haspopup="true" aria-expanded="false" data-display="static">
                            <i class="icon-shopping-cart"></i>
                            <span class="cart-count"><vc:sepet-sayi></vc:sepet-sayi></span>
                            <span class="cart-txt">Sepet</span>
                        </a>

                    </div><!-- End .cart-dropdown -->
                </div>
            </div><!-- End .header-right -->
        </div><!-- End .container -->
    </div><!-- End .header-middle -->

    <div class="header-bottom sticky-header">
        <div class="container">
            <div class="header-left">
                <div class="dropdown category-dropdown show is-on" data-visible="true">
                    <a href="#" class="dropdown-toggle" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true" data-display="static" title="Browse Categories">
                        Kategoriler
                    </a>

                    <div class="dropdown-menu " @* Sadece anasayfa için burda show Yazacak *@>
                        <nav class="side-nav">
                            <ul class="menu-vertical sf-arrows">
                                <li><a asp-controller="UrunlerListesi" asp-action="Index" asp-route-id="3">Bilgisayarlar</a></li>
                                <li><a asp-controller ="UrunlerListesi" asp-action="Index" asp-route-id="4">Yazıcılar</a></li>
                                <li><a asp-controller="UrunlerListesi" asp-action="Index" asp-route-id="5">Toner ve Kartuşlar</a></li>
                                <li><a asp-controller="UrunlerListesi" asp-action="Index" asp-route-id="6">Kırtasiye</a></li>
                                <li><a asp-controller="UrunlerListesi" asp-action="Index" asp-route-id="7">Ofis Malzemeleri</a></li>
               
                            </ul><!-- End .menu-vertical -->
                        </nav><!-- End .side-nav -->
                    </div><!-- End .dropdown-menu -->
                </div><!-- End .category-dropdown -->
            </div><!-- End .col-lg-3 -->
            <div class="header-center">
                <nav class="main-nav">
                    <ul class="menu sf-arrows">
                        <li class="megamenu-container active">
                            <a asp-action="Index" asp-controller="Anasayfa" class="sf-with-ul">AnaSayfa</a>

                        </li>
                        <li class="megamenu-container ">
                            <a asp-action="Index" asp-controller="Hizmetlerimiz" class="sf-with-ul">Hizmetlerimiz</a>

                            <div class="megamenu demo">
                                <div class="menu-col">

                                    <div class="demo-list">
                                        <div class="demo-item">
                                            <a asp-action="GuvenlikSistemleriHizmetleri" asp-controller="Hizmetlerimiz">
                                                <span class="demo-bg" style="background-image: url(/images/kamera.jpg);"></span>
                                                <span class="demo-title">Güvenlik Sitemleri</span>
                                            </a>
                                        </div><!-- End .demo-item -->

                                        <div class="demo-item">
                                            <a asp-action="BilgisayarTeknikServisHizmetleri" asp-controller="HizmeHizmetlerimiztler">
                                                <span class="demo-bg" style="background-image: url(/images/bilgisayar-teknik.jpg);"></span>
                                                <span class="demo-title">Bilgisayar Bakımı</span>
                                            </a>
                                        </div><!-- End .demo-item -->
                                        <div class="demo-item">
                                            <a asp-action="FiberAltyapıHizmetleri" asp-controller="Hizmetlerimiz">
                                                <span class="demo-bg" style="background-image: url(/images/fiber.jpg);"></span>
                                                <span class="demo-title">Fiber ALtyapı</span>
                                            </a>
                                        </div><!-- End .demo-item -->

                                        <div class="demo-item">
                                            <a asp-action="NetworkDataKablolamaHizmetleri" asp-controller="Hizmetlerimiz">
                                                <span class="demo-bg" style="background-image: url(/images/datakablo.jpg);"></span>
                                                <span class="demo-title">Data Kablolama</span>
                                            </a>
                                        </div><!-- End .demo-item -->
                                        <div class="demo-item">
                                            <a asp-action="YaziciTeknikServisHizmetleri" asp-controller="Hizmetlerimiz">
                                                <span class="demo-bg" style="background-image: url(/images/yaziciservis.jpg);"></span>
                                                <span class="demo-title">Yazıcı Teknik Servisi</span>
                                            </a>
                                        </div><!-- End .demo-item -->
                                        <div class="demo-item">
                                            <a asp-action="KartusTonerServisHizmetleri" asp-controller="Hizmetlerimiz">
                                                <span class="demo-bg" style="background-image: url(/images/tonerdolumu.jpg);"></span>
                                                <span class="demo-title">Toner Kartuş Servisi</span>
                                            </a>
                                        </div><!-- End .demo-item -->




                                    </div><!-- End .demo-list -->


                                </div><!-- End .menu-col -->
                            </div><!-- End .megamenu -->
                        </li>

                        <li>
                            <a asp-action="Index" asp-controller="Hakkimizda" class="sf-with-ul">Hakkımızda</a>

                        </li>
                        <li>
                            <a asp-action="Index" asp-controller="Iletisim" class="sf-with-ul">İletişim</a>

                        </li>
                    </ul><!-- End .menu -->
                </nav><!-- End .main-nav -->
            </div><!-- End .col-lg-9 -->
           
        </div><!-- End .container -->
    </div><!-- End .header-bottom -->

</header><!-- End .header -->

Bilgi/Bilgi.Web/Views/Shared/_SepetPartialView.cshtml
@model List<SepetDetayViewModel>
<div class="page-content" id="Tablo">
    <div class="cart">
        <div class="container">
            <div class="row">
                <div class="col-lg-9">
                    <table class="table table-cart table-mobile">
                        <thead>
                            <tr>
                                <th>Ürünler</th>
                                <th>Fiyat</th>
                                <th>Adet</th>
                                <th>Toplam</th>
                                <th></th>
                            </tr>
                        </thead>

                        <tbody>
                            @foreach (var item in Model)
                            {


                                <tr>
                                    <td class="product-col">
                                        <div class="product">
                                            <figure class="product-media">
                                                <a href="#">
                                                    <img src="@item.Urun.ResimUrlKucuk" alt="Product image">
                                                </a>
                                            </figure>

                                            <h3 class="product-title">
                                                <a href="#">@item.Urun.Adi</a>
                                            </h3><!-- End .product-title -->
                                        </div><!-- End .product -->
                                    </td>
                                    <td class="price-col">@item.BirimFiyat.ToString("C")</td>
                                    <td class="quantity-col">
                                        <div class="cart-product-quantity" onclick="adet(@item.UrunId)">
                                            <input id="@item.UrunId" type="number" class="form-control" value="@item.Adet" min="1" max="@item.Urun.Stok" step="1" data-decimals="0" required readonly>
                                        </div><!-- End .cart-product-quantity -->
                                    </td>
                             
                              
                                    <td class="total-col">@item.ToplamTutar.ToString("C")</td>
                                    <td class="remove-col"><a asp-action="SepettenSil" asp-route-id="@item.UrunId" class="btn-remove"><i class="icon-close"></i></a></td>
                                    <td> <input type="hidden" id="urunid-@item.UrunId" value="@item.UrunId" /></td>
                                </tr>
                            }
                        </tbody>
                    </table><!-- End .table table-wishlist -->


                </div><!-- End .col-lg-9 -->
                <aside class="col-lg-3">
                    <div class="summary summary-cart">
                        <h3 class="summary-title">Sepet Toplamı</h3><!-- End .summary-title -->

                        <table class="table table-summary">
                            <tbody>
                                <tr class="summary-subtotal">
                                    <td>Toplam:</td>
                                    <td>
                                        @ViewBag.toplam
                                    </td>
                                </tr><!-- End .summary-subtotal -->




                                <tr class="summary-shipping-estimate">
                                    <td>Estimate for Your Country<br> <a href="dashboard.html">Adresi Değiştir</a></td>
                                    <td>&nbsp;</td>
                                </tr><!-- End .summary-shipping-estimate -->

                                <tr class="summary-total">
                                    <td>Total:</td>
                                    <td>@ViewBag.toplam</td>
                                </tr><!-- End .summary-total -->
                            </tbody>
                        </table><!-- End .table table-summary -->

                        <a href="checkout.html" class="btn btn-outline-primary-2 btn-order btn-block">Alışverişi Tamamla</a>
                    </div><!-- End .summary -->


                </aside><!-- End .col-lg-3 -->
            </div><!-- End .row -->
        </div><!-- End .container -->
    </div><!-- End .cart -->
</div><!-- End .page-content -->