Bilgi/Bilgi.Web/Controllers/Main/UrunDetayController.cs
using AutoMapper;
using Bilgi.Service.Layer.Services.Abstract;
using Bilgi.Web.ViewModel;
using Microsoft.AspNetCore.Mvc;

namespace Bilgi.Web.Controllers.Main
{
    public class UrunDetayController : Controller
    {

        private readonly IUrunService _urunService;
        private readonly IOzellikService _ozellikService;
        private readonly IMapper _mapper;

        public UrunDetayController(IUrunService urunService, IOzellikService ozellikService, IMapper mapper)
        {
            _urunService = urunService;
            _ozellikService = ozellikService;
            _mapper = mapper;
        }

        public IActionResult Index(int id)
        {
            DetayViewModel model = new DetayViewModel()
            {
                Urun = _mapper.Map<UrunViewModel>(_urunService.TGetByIdFiltre(x => x.Id == id)),
                Ozellikler = _mapper.Map<IEnumerable<OzellikViewModel>>(_ozellikService.TGetListAllFiltre(x => x.UrunId == id))
            };

            return View(model);
        }
    }
}

Bilgi/Bilgi.Web/ViewComponents/DetayGenelUrunler/DetayGenelUrunlerViewComponent.cs
using AutoMapper;
using Bilgi.Entity.Layer.Entities;
using Bilgi.Service.Layer.Services.Abstract;
using Bilgi.Web.ViewModel;
using Microsoft.AspNetCore.Mvc;

namespace Bilgi.Web.ViewComponents.DetayGenelUrunler
{
    public class DetayGenelUrunlerViewComponent : ViewComponent
    {
        private readonly IUrunService _urunService;
        private readonly IMapper _mapper;

        public DetayGenelUrunlerViewComponent(IUrunService urunService, IMapper mapper)
        {
            _urunService = urunService;
            _mapper = mapper;
        }

        public IViewComponentResult Invoke()
        {
            Random random = new Random();
            var urunler = _urunService.TGetListAllFiltre(x => x.SatisDurum == true).ToList();

            int urunSayisi = urunler.Count();
            List<Urun> rastgeleUrunler = new List<Urun>();

            if (urunSayisi > 10)
            {
                for (int i = 0; i < 10; i++)
                {
                    int rastgeleIndex = random.Next(0, urunSayisi);
                    rastgeleUrunler.Add(urunler[rastgeleIndex]);
                    urunler.RemoveAt(rastgeleIndex);
                    urunSayisi--;
                }
            }
            else
            {
                rastgeleUrunler = urunler;
            }


            return View(_mapper.Map<IEnumerable<UrunViewModel>>(rastgeleUrunler));

        }
    }
}

Bilgi/Bilgi.Web/Views/Shared/Components/DetayGenelUrunler/Default.cshtml
@model IEnumerable<UrunViewModel>

@foreach (var item in Model)
{
   


        <div class="product">
            <figure class="product-media">

                <a asp-action="Index" asp-controller="UrunDetay" asp-route-id="@item.Id">
                    <img src="@item.ResimUrlKucuk" alt="@item.ResimBaslik" class="product-image">
                </a>


                <div class="product-action">
                    <a href="javascript:void(0);" class="btn-product btn-cart" title="Add to cart" onclick="submitForm(@item.Id, 1)"><span>Sepete Ekle</span></a>
                </div><!-- End .product-action -->
            </figure><!-- End .product-media -->

            <div class="product-body">
                <div class="product-cat">
                    <a href="#">Bilgisayar</a>
                </div><!-- End .product-cat -->

                <h3 class="product-title"><a asp-action="Index" asp-controller="UrunDetay" asp-route-id="@item.Id">@item.Adi</a></h3>

                <!-- End .product-title -->



                <div class="product-price">
                    <span class="price"></span>
                    @item.Fiyat.ToString("C")
                </div><!-- End .product-price -->

            </div><!-- End .product-body -->
        </div>

        <!-- End .product -->
    
} 