Bilgi/Bilgi.Web/Controllers/Main/SepetController.cs
using AutoMapper;
using Bilgi.Entity.Layer.Entities;
using Bilgi.Service.Layer.Services.Abstract;
using Bilgi.Web.Extensions;
using Bilgi.Web.ViewModel;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System.Net;

namespace Bilgi.Web.Controllers.Main
{
    public class SepetController : Controller
    {
        private readonly IUrunService _urunService;
        private readonly ISepetDetayService _sepetDetayService;
        private readonly IMapper _mapper;
    
        List<SepetDetayViewModel> sepet;

        public SepetController(IUrunService urunService, ISepetDetayService sepetDetayService,IMapper mapper)
        {
            _urunService = urunService;
            _sepetDetayService = sepetDetayService;
            _mapper = mapper;           

        }

        public IActionResult Index()
        {
           
            sepet = SepetAl();
            decimal toplam = 0;
            foreach (var item in sepet)
            {
                toplam += item.ToplamTutar;
            }
            ViewBag.toplam = toplam.ToString("C");
            return View(sepet);
        }
        private List<SepetDetayViewModel> SepetAl()
        { 
            var sepet = HttpContext.Session.GetJson<List<SepetDetayViewModel>>("sepet") ?? new List<SepetDetayViewModel>();  //sepet varsa olan sepet yoksa yeni sepet oluşturularak verilir
            return sepet;
        }
      
        public IActionResult SepeteEkle(int id, int Adet)
        {
           
            var urun = _urunService.TGetByIdFiltre(x => x.Id == id && x.SatisDurum==true);  //id den ürün bulunur
            sepet = SepetAl();   //sepet alınır
            SepetDetay siparis = new SepetDetay();   //yeni detay oluşturulur ve içeriği doldurulur
            siparis.Urun = urun;
            siparis.UrunId = urun.Id;
            siparis.Adet = Adet;
            siparis.BirimFiyat = urun.Fiyat;
          
            sepet = _mapper.Map<List<SepetDetayViewModel>>( _sepetDetayService.SepeteEkle(_mapper.Map<List<SepetDetay>>(sepet), siparis)); //sepete yeni detay eklenir
            SepetKaydet(sepet);  //sepet kaydedilir
            return RedirectToAction("Index");  //sepet gösterilir


        }
        public void SepetKaydet(List<SepetDetayViewModel> sepet)
        {
            HttpContext.Session.SetJson("sepet",  (_mapper.Map<List<SepetDetay>>( sepet))); //sepet sessiona kaydedilir
        }
        public IActionResult SepettenSil(int id)
        {
            sepet = SepetAl(); // sepeti al
            sepet.RemoveAll(x => x.UrunId==id); //ürünü sepetten sil
            SepetKaydet(sepet);  //sepeti kaydet
            return RedirectToAction("Index");
        }
        public void AdetGuncelle(int id,int adet)
        {
            sepet = SepetAl();
          var urun = sepet.Find(x => x.UrunId==id);
            urun.ToplamTutar = adet * urun.BirimFiyat;
            urun.Adet=adet;

            SepetKaydet(sepet);
    

        }

        public IActionResult GuncelSepet()   //ajax ile sepeti güncellemek için
        {
            sepet = SepetAl();
            return PartialView("_SepetPartialView", sepet);
        }
        public IActionResult GuncelSepetSayisi()  //ajax ile sepet ürün sayısını güncellemek için
        {
            
            return ViewComponent("SepetSayi");
        }



    }
}

Bilgi/Bilgi.Web/Controllers/Main/UrunDetayController.cs
using AutoMapper;
using Bilgi.Service.Layer.Services.Abstract;
using Bilgi.Web.ViewModel;
using Microsoft.AspNetCore.Mvc;

namespace Bilgi.Web.Controllers.Main
{
    public class UrunDetayController : Controller
    {

        private readonly IUrunService _urunService;
        private readonly IOzellikService _ozellikService;
        private readonly IMapper _mapper;

        public UrunDetayController(IUrunService urunService, IOzellikService ozellikService, IMapper mapper)
        {
            _urunService = urunService;
            _ozellikService = ozellikService;
            _mapper = mapper;
        }

        public IActionResult Index(int id)
        {
            DetayViewModel model = new DetayViewModel()
            {
                Urun = _mapper.Map<UrunViewModel>(_urunService.TGetByIdFiltre(x => x.Id == id)),
                Ozellikler = _mapper.Map<IEnumerable<OzellikViewModel>>(_ozellikService.TGetListAllFiltre(x => x.UrunId == id))
            };

            return View(model);
        }
    }
}

Bilgi/Bilgi.Web/ViewComponents/DetayAside/DetayAsideViewComponent.cs
using AutoMapper;
using Bilgi.Entity.Layer.Entities;
using Bilgi.Service.Layer.Services.Abstract;
using Bilgi.Web.ViewModel;
using Microsoft.AspNetCore.Mvc;
using System;

namespace Bilgi.Web.ViewComponents.DetayAside
{
    public class DetayAsideViewComponent : ViewComponent
    {
        private readonly IUrunService _urunService;
        private readonly IMapper _mapper;

        public DetayAsideViewComponent(IUrunService urunService, IMapper mapper)
        {
            _urunService = urunService;
            _mapper = mapper;
        }

        public IViewComponentResult Invoke(int id)
        {
            Random random = new Random();
            var urunler = _urunService.TGetListAllFiltre(x => x.KategoriId == id&&x.SatisDurum==true).ToList();

            int urunSayisi = urunler.Count();
            List<Urun> rastgeleUrunler = new List<Urun>();

            if (urunSayisi > 3)
            {
                for (int i = 0; i < 3; i++)
                {
                    int rastgeleIndex = random.Next(0, urunSayisi);
                    rastgeleUrunler.Add(urunler[rastgeleIndex]);
                    urunler.RemoveAt(rastgeleIndex);
                    urunSayisi--;
                }
            }
            else
            {
                rastgeleUrunler = urunler;
            }


            return View(_mapper.Map<IEnumerable<UrunViewModel>>(rastgeleUrunler));
        }
    }
}

Bilgi/Bilgi.Web/ViewComponents/DetayGenelUrunler/DetayGenelUrunlerViewComponent.cs
using AutoMapper;
using Bilgi.Entity.Layer.Entities;
using Bilgi.Service.Layer.Services.Abstract;
using Bilgi.Web.ViewModel;
using Microsoft.AspNetCore.Mvc;

namespace Bilgi.Web.ViewComponents.DetayGenelUrunler
{
    public class DetayGenelUrunlerViewComponent : ViewComponent
    {
        private readonly IUrunService _urunService;
        private readonly IMapper _mapper;

        public DetayGenelUrunlerViewComponent(IUrunService urunService, IMapper mapper)
        {
            _urunService = urunService;
            _mapper = mapper;
        }

        public IViewComponentResult Invoke()
        {
            Random random = new Random();
            var urunler = _urunService.TGetListAllFiltre(x => x.SatisDurum == true).ToList();

            int urunSayisi = urunler.Count();
            List<Urun> rastgeleUrunler = new List<Urun>();

            if (urunSayisi > 10)
            {
                for (int i = 0; i < 10; i++)
                {
                    int rastgeleIndex = random.Next(0, urunSayisi);
                    rastgeleUrunler.Add(urunler[rastgeleIndex]);
                    urunler.RemoveAt(rastgeleIndex);
                    urunSayisi--;
                }
            }
            else
            {
                rastgeleUrunler = urunler;
            }


            return View(_mapper.Map<IEnumerable<UrunViewModel>>(rastgeleUrunler));

        }
    }
}

Bilgi/Bilgi.Web/Views/UrunDetay/Index.cshtml
@model DetayViewModel
@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/MainLayout/_MainLayout.cshtml";
}


<main class="main">
    <nav aria-label="breadcrumb" class="breadcrumb-nav border-0 mb-0">
        <div class="container d-flex align-items-center">
        </div><!-- End .container -->
    </nav><!-- End .breadcrumb-nav -->

    <div class="page-content">
        <div class="container">
            <div class="row">
                <div class="col-lg-9">
                    <div class="product-details-top">
                        <div class="row">
                            <div class="col-md-6">
                                <div class="product-gallery">
                                    <figure class="product-main-image">
                                        <img id="product-zoom" src="@Model.Urun.ResimUrl1" alt="product image">
                                    </figure><!-- End .product-main-image -->

                                    <div id="product-zoom-gallery" class="product-image-gallery">
                                        <a class="product-gallery-item active" href="#" data-image="@Model.Urun.ResimUrl1">
                                            <img src="@Model.Urun.ResimUrl1" alt="product side">
                                        </a>

                                        <a class="product-gallery-item" href="#" data-image="@Model.Urun.ResimUrl2">
                                            <img src="@Model.Urun.ResimUrl2" alt="product cross">
                                        </a>

                                        <a class="product-gallery-item" href="#" data-image="@Model.Urun.ResimUrl3">
                                            <img src="@Model.Urun.ResimUrl3" alt="product with model">
                                        </a>

                                        <a class="product-gallery-item" href="#" data-image="@Model.Urun.ResimUrlKucuk">
                                            <img src="@Model.Urun.ResimUrlKucuk" alt="product back">
                                        </a>
                                    </div><!-- End .product-image-gallery -->
                                </div><!-- End .product-gallery -->
                            </div><!-- End .col-md-6 -->

                            <div class="col-md-6">
                                <div class="product-details product-details-sidebar">
                                    <h1 class="product-title"><strong>@Model.Urun.Adi</strong></h1><!-- End .product-title -->


                                </div><!-- End .rating-container -->

                                <div class="product-price" style="font-size:28px!important">
                                    @Model.Urun.Fiyat.ToString("C")
                                </div><!-- End .product-price -->

                                <div class="product-content">
                                </div><!-- End .product-content -->
                                @foreach (var item in Model.Ozellikler)
                                {


                                    <div class="details-row details-size">
                                        <label><b>@item.Key:</b></label>

                                        @item.Value
                                    </div>

                                    <!-- End .details-filter-row -->
                                }
                                <form asp-action="SepeteEkle" asp-controller="Sepet" method="get">
                                    <input name="id" value="@Model.Urun.Id" type="hidden" />
                                    <div class="product-details-action">
                                        <div class="details-action-col">
                                            <label for="qty">Adet:</label>
                                            <div class="product-details-quantity">
                                                <input type="number" id="qty" class="form-control" value="1" min="1" max="@Model.Urun.Stok" name="Adet" step="1" data-decimals="0" required>
                                            </div><!-- End .product-details-quantity -->

                                            <input type="submit" class="btn-product btn-cart" value="Sepete Ekle" />
                                        </div><!-- End .details-action-col -->


                                    </div><!-- End .product-details-action -->
                                </form>
                                <div class="product-details-footer details-footer-col">
                                    <div class="product-cat">
                                        <span>Category:</span>
                                        <a href="#">Women</a>,
                                        <a href="#">Dresses</a>,
                                        <a href="#">Yellow</a>
                                    </div><!-- End .product-cat -->

                                    <div class="social-icons social-icons-sm">
                                        <span class="social-label">Share:</span>
                                        <a href="#" class="social-icon" title="Facebook" target="_blank"><i class="icon-facebook-f"></i></a>
                                        <a href="#" class="social-icon" title="Twitter" target="_blank"><i class="icon-twitter"></i></a>
                                        <a href="#" class="social-icon" title="Instagram" target="_blank"><i class="icon-instagram"></i></a>
                                        <a href="#" class="social-icon" title="Pinterest" target="_blank"><i class="icon-pinterest"></i></a>
                                    </div>
                                </div><!-- End .product-details-footer -->
                            </div><!-- End .product-details -->
                        </div><!-- End .row -->
                    </div><!-- End .product-details-top -->

                    <div class="product-details-tab">
                        <ul class="nav nav-pills justify-content-center" role="tablist">
                            <li class="nav-item">
                                <a class="nav-link active" id="product-desc-link" data-toggle="tab" href="#product-desc-tab" role="tab" aria-controls="product-desc-tab" aria-selected="true">Ürün Açıklaması</a>
                            </li>

                        </ul>
                        <div class="tab-content">
                            <div class="tab-pane fade show active" id="product-desc-tab" role="tabpanel" aria-labelledby="product-desc-link">
                                <div class="product-desc-content">

                                    <p>@Model.Urun.Aciklama</p>
                                </div><!-- End .product-desc-content -->
                            </div><!-- .End .tab-pane -->
                        </div><!-- End .tab-content -->
                    </div><!-- End .product-details-tab -->

                    <h2 class="title text-center mb-4">İlginizi Çekebilecek Ürünler</h2><!-- End .title text-center -->
                    <div class="owl-carousel owl-simple carousel-equal-height carousel-with-shadow" data-toggle="owl"
                         data-owl-options='{
                                    "nav": false,
                                    "dots": true,
                                    "margin": 20,
                                    "loop": false,
                                    "responsive": {
                                        "0": {
                                            "items":1
                                        },
                                        "480": {
                                            "items":2
                                        },
                                        "768": {
                                            "items":3
                                        },
                                        "992": {
                                            "items":4
                                        },
                                        "1200": {
                                            "items":4,
                                            "nav": true,
                                            "dots": false
                                        }
                                    }
                                }'>
                       <vc:detay-genel-urunler></vc:detay-genel-urunler>


                    </div><!-- End .owl-carousel -->
                </div><!-- End .col-lg-9 -->

                <aside class="col-lg-3">
                    @await Component.InvokeAsync("DetayAside", new { id = Model.Urun.KategoriId })
                </aside><!-- End .col-lg-3 -->
            </div><!-- End .row -->

        </div><!-- End .container -->
    </div><!-- End .page-content -->
</main><!-- End .main -->


@section Scripts{
    <script>

        document.addEventListener("DOMContentLoaded", function () {
            var galleryItems = document.querySelectorAll(".product-gallery-item");
            var zoomImage = document.getElementById("product-zoom");

            galleryItems.forEach(function (item) {
                item.addEventListener("click", function (event) {
                    event.preventDefault();
                    var imageUrl = item.getAttribute("data-image");
                    zoomImage.setAttribute("src", imageUrl);

                    // Active sınıfını güncelle
                    galleryItems.forEach(function (item) {
                        item.classList.remove("active");
                    });
                    item.classList.add("active");
                });
            });
        });
    </script>

}